//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mitoSoft.homeNet.ArduinoIDE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mitoSoft.homeNet.ArduinoIDE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Error.
        /// </summary>
        public static string App_BackgroundErrorTitle {
            get {
                return ResourceManager.GetString("App_BackgroundErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A critical error occurred:
        ///
        ///{0}
        ///
        ///The application will be closed..
        /// </summary>
        public static string App_CriticalError {
            get {
                return ResourceManager.GetString("App_CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Error.
        /// </summary>
        public static string App_CriticalErrorTitle {
            get {
                return ResourceManager.GetString("App_CriticalErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        public static string App_ErrorTitle {
            get {
                return ResourceManager.GetString("App_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred:
        ///
        ///{0}.
        /// </summary>
        public static string App_UnexpectedError {
            get {
                return ResourceManager.GetString("App_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print / Export.
        /// </summary>
        public static string Button_PrintExport {
            get {
                return ResourceManager.GetString("Button_PrintExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info.
        /// </summary>
        public static string Col_AdditionalInfo {
            get {
                return ResourceManager.GetString("Col_AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Col_Description {
            get {
                return ResourceManager.GetString("Col_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPIO Pins.
        /// </summary>
        public static string Col_GpioPins {
            get {
                return ResourceManager.GetString("Col_GpioPins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Col_Name {
            get {
                return ResourceManager.GetString("Col_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Col_Type {
            get {
                return ResourceManager.GetString("Col_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP: {0} | MAC: {1} | Used GPIOs: {2}.
        /// </summary>
        public static string Doc_ControllerInfo {
            get {
                return ResourceManager.GetString("Doc_ControllerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller: {0} (ID: {1}).
        /// </summary>
        public static string Doc_ControllerTitle {
            get {
                return ResourceManager.GetString("Doc_ControllerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created: {0}.
        /// </summary>
        public static string Doc_CreatedAt {
            get {
                return ResourceManager.GetString("Doc_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No controllers with GPIOs found..
        /// </summary>
        public static string Doc_NoData {
            get {
                return ResourceManager.GetString("Doc_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   No devices configured.
        /// </summary>
        public static string Doc_NoDevices {
            get {
                return ResourceManager.GetString("Doc_NoDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPIO Overview - Cabinet Documentation.
        /// </summary>
        public static string Doc_Title {
            get {
                return ResourceManager.GetString("Doc_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arduino files (*.ino)|*.ino|Text files (*.txt)|*.txt|All files (*.*)|*.*.
        /// </summary>
        public static string Filter_Arduino {
            get {
                return ResourceManager.GetString("Filter_Arduino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML files (*.yaml)|*.yaml|All files (*.*)|*.*.
        /// </summary>
        public static string Filter_Yaml {
            get {
                return ResourceManager.GetString("Filter_Yaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close (Esc).
        /// </summary>
        public static string FindBar_Close {
            get {
                return ResourceManager.GetString("FindBar_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string FindBar_FindNext {
            get {
                return ResourceManager.GetString("FindBar_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find:.
        /// </summary>
        public static string FindBar_Label {
            get {
                return ResourceManager.GetString("FindBar_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select controller:.
        /// </summary>
        public static string Label_SelectController {
            get {
                return ResourceManager.GetString("Label_SelectController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom:.
        /// </summary>
        public static string Label_Zoom {
            get {
                return ResourceManager.GetString("Label_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Controller.
        /// </summary>
        public static string Menu_Controllers {
            get {
                return ResourceManager.GetString("Menu_Controllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to _Clipboard.
        /// </summary>
        public static string Menu_CopyToClipboard {
            get {
                return ResourceManager.GetString("Menu_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Errors / Warnings.
        /// </summary>
        public static string Menu_ErrorsWarnings {
            get {
                return ResourceManager.GetString("Menu_ErrorsWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Find....
        /// </summary>
        public static string Menu_Find {
            get {
                return ResourceManager.GetString("Menu_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _GPIO Documentation.
        /// </summary>
        public static string Menu_GpioDocumentation {
            get {
                return ResourceManager.GetString("Menu_GpioDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing HomeNet Elements.
        /// </summary>
        public static string Menu_MissingHomeNetElements {
            get {
                return ResourceManager.GetString("Menu_MissingHomeNetElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string Menu_Open {
            get {
                return ResourceManager.GetString("Menu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        public static string Menu_SaveAs {
            get {
                return ResourceManager.GetString("Menu_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shows which .
        /// </summary>
        public static string MissingElements_Description {
            get {
                return ResourceManager.GetString("MissingElements_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  entries you still need to add to your YAML so that all MQTT devices also have a homeNet configuration..
        /// </summary>
        public static string MissingElements_TextAfter {
            get {
                return ResourceManager.GetString("MissingElements_TextAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to homeNet:.
        /// </summary>
        public static string MissingElements_TextBold {
            get {
                return ResourceManager.GetString("MissingElements_TextBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during build &apos;{0}&apos;: {1}.
        /// </summary>
        public static string Msg_BuildError {
            get {
                return ResourceManager.GetString("Msg_BuildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build failed: &apos;{0}&apos;.
        /// </summary>
        public static string Msg_BuildFailed {
            get {
                return ResourceManager.GetString("Msg_BuildFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build successful: {0}.
        /// </summary>
        public static string Msg_BuildSuccessful {
            get {
                return ResourceManager.GetString("Msg_BuildSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller not found....
        /// </summary>
        public static string Msg_ControllerNotFound {
            get {
                return ResourceManager.GetString("Msg_ControllerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content copied to clipboard.
        /// </summary>
        public static string Msg_CopiedToClipboard {
            get {
                return ResourceManager.GetString("Msg_CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPIO documentation created.
        /// </summary>
        public static string Msg_GpioDocumentationCreated {
            get {
                return ResourceManager.GetString("Msg_GpioDocumentationCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No controller selected....
        /// </summary>
        public static string Msg_NoControllerSelected {
            get {
                return ResourceManager.GetString("Msg_NoControllerSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No controllers with GPIOs found.
        ///
        ///Please ensure your YAML file contains valid homeNet controllers with Cover or Light configurations..
        /// </summary>
        public static string Msg_NoControllersWithGpios {
            get {
                return ResourceManager.GetString("Msg_NoControllersWithGpios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No warnings found....
        /// </summary>
        public static string Msg_NoWarningsFound {
            get {
                return ResourceManager.GetString("Msg_NoWarningsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened: {0}.
        /// </summary>
        public static string Msg_Opened {
            get {
                return ResourceManager.GetString("Msg_Opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error printing: {0}.
        /// </summary>
        public static string Msg_PrintError {
            get {
                return ResourceManager.GetString("Msg_PrintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document sent to printer..
        /// </summary>
        public static string Msg_PrintSuccess {
            get {
                return ResourceManager.GetString("Msg_PrintSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Msg_PrintSuccessTitle {
            get {
                return ResourceManager.GetString("Msg_PrintSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved: {0}.
        /// </summary>
        public static string Msg_Saved {
            get {
                return ResourceManager.GetString("Msg_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        public static string Title_Controllers {
            get {
                return ResourceManager.GetString("Title_Controllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors / Warnings.
        /// </summary>
        public static string Title_ErrorsWarnings {
            get {
                return ResourceManager.GetString("Title_ErrorsWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML Editor.
        /// </summary>
        public static string Title_YamlEditor {
            get {
                return ResourceManager.GetString("Title_YamlEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Arduino code.
        /// </summary>
        public static string Tooltip_Build {
            get {
                return ResourceManager.GetString("Tooltip_Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check errors and warnings.
        /// </summary>
        public static string Tooltip_Check {
            get {
                return ResourceManager.GetString("Tooltip_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy active content to clipboard.
        /// </summary>
        public static string Tooltip_CopyToClipboard {
            get {
                return ResourceManager.GetString("Tooltip_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find (Ctrl+F).
        /// </summary>
        public static string Tooltip_Find {
            get {
                return ResourceManager.GetString("Tooltip_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment selected lines.
        /// </summary>
        public static string YamlView_CommentTooltip {
            get {
                return ResourceManager.GetString("YamlView_CommentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select homeNet node.
        /// </summary>
        public static string YamlView_SelectHomeNetTooltip {
            get {
                return ResourceManager.GetString("YamlView_SelectHomeNetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncomment selected lines.
        /// </summary>
        public static string YamlView_UncommentTooltip {
            get {
                return ResourceManager.GetString("YamlView_UncommentTooltip", resourceCulture);
            }
        }
    }
}
